pipeline:
  name: test-pipe-12354
  identifier: testpipe12354
  projectIdentifier: testproj
  orgIdentifier: testprameet
  tags: {}
  stages:
    - stage:
        name: as
        identifier: as
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "ASWED"
                          exit -1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - parallel:
                  - stepGroup:
                      name: test-sg
                      identifier: testsg
                      steps:
                        - step:
                            type: ShellScript
                            name: ShellScript_2
                            identifier: ShellScript_2
                            spec:
                              shell: Bash
                              executionTarget: {}
                              source:
                                type: Inline
                                spec:
                                  script: echo "123456"
                              environmentVariables: []
                              outputVariables: []
                            timeout: 10m
                      when:
                        stageStatus: Success
                  - stepGroup:
                      name: failure
                      identifier: failure
                      steps:
                        - step:
                            type: ShellScript
                            name: ShellScript_3
                            identifier: ShellScript_3
                            spec:
                              shell: Bash
                              executionTarget: {}
                              source:
                                type: Inline
                                spec:
                                  script: echo "Heloo from shell scrip 3"
                              environmentVariables: []
                              outputVariables: []
                            timeout: 10m
                      when:
                        stageStatus: Success
        tags: {}
