pipeline:
  name: test-pi-trigger
  identifier: testpitrigger
  projectIdentifier: testproj
  orgIdentifier: testprameet
  tags: {}
  stages:
    - stage:
        name: test-pi-stage
        identifier: testpistage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "1234"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
